displayName=Fullscreen
author=dekvall
support=https://github.com/dekvall/runelite-external-plugins/tree/fullscreen
description=RuneLite, but in fullscreen.
tags=window,full,screen,all,monitor,exclusive,borderless
plugins=dekvall.fullscreen.FullscreenPlugin
version=2.0
build=standard
