package dev.dkvl.womutils.beans;

import com.google.gson.annotations.SerializedName;
import dev.dkvl.womutils.WomUtilsPlugin;
import java.awt.image.BufferedImage;
import net.runelite.client.util.ImageUtil;

public enum Metric
{
	@SerializedName("abyssal_sire")
	ABYSSAL_SIRE,
	@SerializedName("agility")
	AGILITY,
	@SerializedName("alchemical_hydra")
	ALCHEMICAL_HYDRA,
	@SerializedName("attack")
	ATTACK,
	@SerializedName("barrows_chests")
	BARROWS_CHESTS,
	@SerializedName("bossing")
	BOSSING,
	@SerializedName("bounty_hunter_hunter")
	BOUNTY_HUNTER_HUNTER,
	@SerializedName("bounty_hunter_rogue")
	BOUNTY_HUNTER_ROGUE,
	@SerializedName("bryophyta")
	BRYOPHYTA,
	@SerializedName("callisto")
	CALLISTO,
	@SerializedName("cerberus")
	CERBERUS,
	@SerializedName("chambers_of_xeric_challenge_mode")
	CHAMBERS_OF_XERIC_CHALLENGE_MODE,
	@SerializedName("chambers_of_xeric")
	CHAMBERS_OF_XERIC,
	@SerializedName("chaos_elemental")
	CHAOS_ELEMENTAL,
	@SerializedName("chaos_fanatic")
	CHAOS_FANATIC,
	@SerializedName("clue_scrolls_all")
	CLUE_SCROLLS_ALL,
	@SerializedName("clue_scrolls_beginner")
	CLUE_SCROLLS_BEGINNER,
	@SerializedName("clue_scrolls_easy")
	CLUE_SCROLLS_EASY,
	@SerializedName("clue_scrolls_elite")
	CLUE_SCROLLS_ELITE,
	@SerializedName("clue_scrolls_hard")
	CLUE_SCROLLS_HARD,
	@SerializedName("clue_scrolls_master")
	CLUE_SCROLLS_MASTER,
	@SerializedName("clue_scrolls_medium")
	CLUE_SCROLLS_MEDIUM,
	@SerializedName("combat")
	COMBAT,
	@SerializedName("commander_zilyana")
	COMMANDER_ZILYANA,
	@SerializedName("construction")
	CONSTRUCTION,
	@SerializedName("cooking")
	COOKING,
	@SerializedName("corporeal_beast")
	CORPOREAL_BEAST,
	@SerializedName("crafting")
	CRAFTING,
	@SerializedName("crazy_archaeologist")
	CRAZY_ARCHAEOLOGIST,
	@SerializedName("dagannoth_prime")
	DAGANNOTH_PRIME,
	@SerializedName("dagannoth_rex")
	DAGANNOTH_REX,
	@SerializedName("dagannoth_supreme")
	DAGANNOTH_SUPREME,
	@SerializedName("defence")
	DEFENCE,
	@SerializedName("deranged_archaeologist")
	DERANGED_ARCHAEOLOGIST,
	@SerializedName("ehb")
	EHB,
	@SerializedName("ehp")
	EHP,
	@SerializedName("farming")
	FARMING,
	@SerializedName("firemaking")
	FIREMAKING,
	@SerializedName("fishing")
	FISHING,
	@SerializedName("fletching")
	FLETCHING,
	@SerializedName("general_graardor")
	GENERAL_GRAARDOR,
	@SerializedName("giant_mole")
	GIANT_MOLE,
	@SerializedName("grotesque_guardians")
	GROTESQUE_GUARDIANS,
	@SerializedName("herblore")
	HERBLORE,
	@SerializedName("hespori")
	HESPORI,
	@SerializedName("hitpoints")
	HITPOINTS,
	@SerializedName("hunter")
	HUNTER,
	@SerializedName("kalphite_queen")
	KALPHITE_QUEEN,
	@SerializedName("king_black_dragon")
	KING_BLACK_DRAGON,
	@SerializedName("kraken")
	KRAKEN,
	@SerializedName("kreearra")
	KREEARRA,
	@SerializedName("kril_tsutsaroth")
	KRIL_TSUTSAROTH,
	@SerializedName("last_man_standing")
	LAST_MAN_STANDING,
	@SerializedName("league_points")
	LEAGUE_POINTS,
	@SerializedName("magic")
	MAGIC,
	@SerializedName("mimic")
	MIMIC,
	@SerializedName("mining")
	MINING,
	@SerializedName("nightmare")
	NIGHTMARE,
	@SerializedName("obor")
	OBOR,
	@SerializedName("overall")
	OVERALL,
	@SerializedName("phosanis_nightmare")
	PHOSANIS_NIGHTMARE,
	@SerializedName("prayer")
	PRAYER,
	@SerializedName("ranged")
	RANGED,
	@SerializedName("runecrafting")
	RUNECRAFTING,
	@SerializedName("sarachnis")
	SARACHNIS,
	@SerializedName("scorpia")
	SCORPIA,
	@SerializedName("skotizo")
	SKOTIZO,
	@SerializedName("slayer")
	SLAYER,
	@SerializedName("smithing")
	SMITHING,
	@SerializedName("soul_wars_zeal")
	SOUL_WARS_ZEAL,
	@SerializedName("strength")
	STRENGTH,
	@SerializedName("tempoross")
	TEMPOROSS,
	@SerializedName("theatre_of_blood_hard_mode")
	THEATRE_OF_BLOOD_HARD_MODE,
	@SerializedName("theatre_of_blood")
	THEATRE_OF_BLOOD,
	@SerializedName("the_corrupted_gauntlet")
	THE_CORRUPTED_GAUNTLET,
	@SerializedName("the_gauntlet")
	THE_GAUNTLET,
	@SerializedName("thermonuclear_smoke_devil")
	THERMONUCLEAR_SMOKE_DEVIL,
	@SerializedName("thieving")
	THIEVING,
	@SerializedName("tt200m")
	TT200M,
	@SerializedName("ttm")
	TTM,
	@SerializedName("tzkal_zuk")
	TZKAL_ZUK,
	@SerializedName("tztok_jad")
	TZTOK_JAD,
	@SerializedName("venenatis")
	VENENATIS,
	@SerializedName("vetion")
	VETION,
	@SerializedName("vorkath")
	VORKATH,
	@SerializedName("wintertodt")
	WINTERTODT,
	@SerializedName("woodcutting")
	WOODCUTTING,
	@SerializedName("zalcano")
	ZALCANO,
	@SerializedName("zulrah")
	ZULRAH,
	;

	public BufferedImage loadImage()
	{
		return ImageUtil.loadImageResource(WomUtilsPlugin.class, "metrics/" + name().toLowerCase() + ".png");
	}
}
