package dev.dkvl.womutils.beans;

import lombok.Value;
import net.runelite.client.hiscore.HiscoreSkill;

@Value
public class SnapshotBosses
{
    Boss abyssal_sire;
    Boss alchemical_hydra;
    Boss artio;
    Boss barrows_chests;
    Boss bryophyta;
    Boss callisto;
    Boss calvarion;
    Boss cerberus;
    Boss chambers_of_xeric;
    Boss chambers_of_xeric_challenge_mode;
    Boss chaos_elemental;
    Boss chaos_fanatic;
    Boss commander_zilyana;
    Boss corporeal_beast;
    Boss crazy_archaeologist;
    Boss dagannoth_prime;
    Boss dagannoth_rex;
    Boss dagannoth_supreme;
    Boss deranged_archaeologist;
    Boss general_graardor;
    Boss giant_mole;
    Boss grotesque_guardians;
    Boss hespori;
    Boss kalphite_queen;
    Boss king_black_dragon;
    Boss kraken;
    Boss kreearra;
    Boss kril_tsutsaroth;
    Boss mimic;
    Boss nex;
    Boss nightmare;
    Boss phosanis_nightmare;
    Boss obor;
    Boss phantom_muspah;
    Boss sarachnis;
    Boss scorpia;
    Boss skotizo;
    Boss spindel;
    Boss tempoross;
    Boss the_gauntlet;
    Boss the_corrupted_gauntlet;
    Boss theatre_of_blood;
    Boss theatre_of_blood_hard_mode;
    Boss thermonuclear_smoke_devil;
    Boss tombs_of_amascut;
    Boss tombs_of_amascut_expert;
    Boss tzkal_zuk;
    Boss tztok_jad;
    Boss venenatis;
    Boss vetion;
    Boss vorkath;
    Boss wintertodt;
    Boss zalcano;
    Boss zulrah;

    public Boss getBoss(HiscoreSkill skill)
    {
        switch(skill)
        {
            case ABYSSAL_SIRE:
                return getAbyssal_sire();
            case ALCHEMICAL_HYDRA:
                return getAlchemical_hydra();
            case ARTIO:
                return getArtio();
            case BARROWS_CHESTS:
                return getBarrows_chests();
            case BRYOPHYTA:
                return getBryophyta();
            case CALLISTO:
                return getCallisto();
            case CALVARION:
                return getCalvarion();
            case CERBERUS:
                return getCerberus();
            case CHAMBERS_OF_XERIC:
                return getChambers_of_xeric();
            case CHAMBERS_OF_XERIC_CHALLENGE_MODE:
                return getChambers_of_xeric_challenge_mode();
            case CHAOS_ELEMENTAL:
                return getChaos_elemental();
            case CHAOS_FANATIC:
                return getChaos_fanatic();
            case COMMANDER_ZILYANA:
                return getCommander_zilyana();
            case CORPOREAL_BEAST:
                return getCorporeal_beast();
            case CRAZY_ARCHAEOLOGIST:
                return getCrazy_archaeologist();
            case DAGANNOTH_PRIME:
                return getDagannoth_prime();
            case DAGANNOTH_REX:
                return getDagannoth_rex();
            case DAGANNOTH_SUPREME:
                return getDagannoth_supreme();
            case DERANGED_ARCHAEOLOGIST:
                return getDeranged_archaeologist();
            case GENERAL_GRAARDOR:
                return getGeneral_graardor();
            case GIANT_MOLE:
                return getGiant_mole();
            case GROTESQUE_GUARDIANS:
                return getGrotesque_guardians();
            case HESPORI:
                return hespori;
            case KALPHITE_QUEEN:
                return getKalphite_queen();
            case KING_BLACK_DRAGON:
                return getKing_black_dragon();
            case KRAKEN:
                return getKraken();
            case KREEARRA:
                return getKreearra();
            case KRIL_TSUTSAROTH:
                return getKril_tsutsaroth();
            case MIMIC:
                return getMimic();
            case NEX:
                return getNex();
            case NIGHTMARE:
                return getNightmare();
            case PHOSANIS_NIGHTMARE:
                return getPhosanis_nightmare();
            case OBOR:
                return getObor();
            case PHANTOM_MUSPAH:
                return getPhantom_muspah();
            case SARACHNIS:
                return getSarachnis();
            case SCORPIA:
                return getScorpia();
            case SKOTIZO:
                return getSkotizo();
            case SPINDEL:
                return getSpindel();
            case TEMPOROSS:
                return getTempoross();
            case THE_GAUNTLET:
                return getThe_gauntlet();
            case THE_CORRUPTED_GAUNTLET:
                return getThe_corrupted_gauntlet();
            case THEATRE_OF_BLOOD:
                return getTheatre_of_blood();
            case THEATRE_OF_BLOOD_HARD_MODE:
                return getTheatre_of_blood_hard_mode();
            case THERMONUCLEAR_SMOKE_DEVIL:
                return getThermonuclear_smoke_devil();
            case TOMBS_OF_AMASCUT:
                return getTombs_of_amascut();
            case TOMBS_OF_AMASCUT_EXPERT:
                return getTombs_of_amascut_expert();
            case TZKAL_ZUK:
                return getTzkal_zuk();
            case TZTOK_JAD:
                return getTztok_jad();
            case VENENATIS:
                return getVenenatis();
            case VETION:
                return getVetion();
            case VORKATH:
                return getVorkath();
            case WINTERTODT:
                return getWintertodt();
            case ZALCANO:
                return getZalcano();
            case ZULRAH:
                return getZulrah();
            default:
                throw new IllegalArgumentException("Invalid hiscore boss");
        }
    }
}
